### ISSUE TITLE
released hackney_telemetry depends on telemetry `1.0.0`

### ISSUE THREAD

**Issue by v0idpwn** [msramos/hackney_telemetry#1]
Hi, @msramos, thanks for the work in the library :), we adopted it a while ago, but there's a problem with dependencies 
that is a bit annoying.

While in the repository `rebar.config` specifies a dependency on `telemetry` `~> 1.0`:
https://github.com/msramos/hackney_telemetry/blob/d1d0dd854aae6ac322fab7aa53211f5bcd9ce6b9/rebar.config#L3

In the `v0.1.1` release in hex `hackney_telemetry` depends on `telemetry` `1.0.0`:
![image](https://github.com/msramos/hackney_telemetry/assets/14948182/f2dfe9c1-cca7-41b5-94ff-a9d18411f61b)
ref: https://hex.pm/packages/hackney_telemetry/0.1.1

This forces dependents using different versions of `telemetry` to override the telemetry dependency. Would it be possible to release a new version depending on `telemetry` `~> 1.0`?

**Comment by msramos** [comment]
@v0idpwn sure! I'll do this later today. Thanks :)

**Comment by msramos** [comment]
@v0idpwn sorry for the delay. I just published version `0.2.0` which fixes this problem with. `temeletry` version, but I also ended up updating CI, Erlang, rebar the formatter among other things.

**Comment by v0idpwn** [comment]
np, thank you so much! :)
